// automatically generated by the FlatBuffers compiler, do not modify

package cz.radovanmoncek.ship.tables;

@SuppressWarnings("unused")
public final class Character {
  private Character() { }
  public static final byte BLUE = 0;
  public static final byte RED = 1;

  public static final String[] names = { "BLUE", "RED", };

  public static String name(int e) { return names[e]; }
}

